# core/opreturn.py
from __future__ import annotations

OP_RETURN_MAX_PAYLOAD = 223  # politique commune wallets/outils BCH


def build_op_return(payload: bytes) -> bytes:
    """
    Build standard OP_RETURN script for a single data push.
    Supports payload up to 223 bytes (common wallet/tool policy).
    """
    if not isinstance(payload, (bytes, bytearray, memoryview)):
        raise TypeError("payload must be bytes-like")
    payload = bytes(payload)

    if len(payload) > 223:
        raise ValueError("OP_RETURN payload too large (>223)")

    l = len(payload)
    if l <= 75:
        # OP_RETURN <len> <data>
        return b"\x6a" + bytes([l]) + payload
    else:
        # OP_RETURN OP_PUSHDATA1 <len> <data>
        return b"\x6a" + b"\x4c" + bytes([l]) + payload


def parse_op_return(script: bytes) -> bytes:
    """
    Parse OP_RETURN script generated by build_op_return.
    """
    if not isinstance(script, (bytes, bytearray, memoryview)):
        raise TypeError("script must be bytes-like")
    b = bytes(script)

    if len(b) < 2 or b[0] != 0x6a:
        raise ValueError("Not OP_RETURN")

    op = b[1]
    if op <= 75:
        ln = op
        start = 2
    elif op == 0x4c:
        if len(b) < 3:
            raise ValueError("Truncated PUSHDATA1")
        ln = b[2]
        start = 3
    else:
        raise ValueError(f"Unsupported push opcode: {op:#x}")

    if len(b) < start + ln:
        raise ValueError("Truncated payload")

    return b[start:start+ln]